# Generated by Django 4.2.27 on 2025-12-04 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredentials',
            name='default_calendar_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CalendarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('event', 'Event'), ('task', 'Task'), ('appointment', 'Appointment')], max_length=20)),
                ('title', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('due_at', models.DateField(blank=True, null=True)),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_item_id', models.CharField(blank=True, max_length=255, null=True)),
                ('is_holiday', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('failed', 'Failed')], default='pending', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'google_calendar_id'], name='authapp_cal_user_id_1e353d_idx'), models.Index(fields=['google_item_id'], name='authapp_cal_google__9519eb_idx')],
            },
        ),
    ]
