# Generated by Django 4.2.27 on 2025-12-04 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_googlecredentials_default_calendar_id_calendaritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='googlecredentials',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='googlecredentials',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
